app_name: "MSBX5420 Final Project"
env: "cluster"

paths:
  rraw: "s3://msbx5420-2026/teams/team_15/data/raw/credit_card_transactions.csv"


spark:
  master: null                          # cluster provides this
  shuffle_partitions: 200